### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by k-goncharova** [Sikerdebaard/dutchcovid19data#1]
Hello, 

Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/QJL5QS

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by Sikerdebaard** [comment]
This data is just a mirror from the Stichting-NICE website, an organisation that focusses on registering data around COVID patients in the ICUs and hospitals in the Netherlands. If you are interested in this data, you need to contact them directly, as I don't own this data.

info@stichting-nice.nl

**Comment by k-goncharova** [comment]
Got it, thank you.
