### ISSUE TITLE
No more automatic update of the datafiles?

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/dutchcovid19data#2]
Hi,

Can you please check if / why the automatic update of the datafiles stopped since today/yesterday?

Many thanks in advance, Wouter

PS This is possibly because the link  https://www.stichting-nice.nl/covid-19/public/zkh/ic-count/ is not available? I have sent an email to NICE asking about this and will share the outcome.

**Comment by Sikerdebaard** [comment]
Unfortunately the server that collects and pushes the data is located in a datacenter where they had a massive power issue. For now I've moved the script to another server until the issue is resolved. Updates should continue on an hourly basis this way.

Thanks for reporting this!

**Comment by wbijster** [comment]
Ok, so not related to NICE at all :), many thanks for your efforts!

**Comment by Sikerdebaard** [comment]
Gebruikt allecijfers.nl dit als databron? If so: nice. ;)

**Comment by wbijster** [comment]
Yes, it does, I changed from NICE to your source in August when I went to France :)
And I just made a switch to use either NICE or this source, in case there is a power issue.

PS The IC-count works fine with NICE, I guess this was just a temporary timeout.

PS2 There are 3 more sources with NICE, not sure if you are aware:

'zkh-intake-count': 'https://www.stichting-nice.nl/covid-19/public/zkh/intake-count/',
'zkh-new-intake': 'https://www.stichting-nice.nl/covid-19/public/zkh/new-intake/',
'zkh-intake-cumulative': 'https://www.stichting-nice.nl/covid-19/public/zkh/intake-cumulative/'

**Comment by Sikerdebaard** [comment]
That's really cool. :+1: 

New url's are automatically extracted from the Stichting NICE website and added to this dataset, so these are already available in the dataset:

https://github.com/Sikerdebaard/dutchcovid19data/blob/master/data/hospitalized/intake-count.json
https://github.com/Sikerdebaard/dutchcovid19data/blob/master/data/hospitalized/new-intake.json
https://github.com/Sikerdebaard/dutchcovid19data/blob/master/data/hospitalized/intake-cumulative.json

**Comment by wbijster** [comment]
Well done, that automatic extraction! Aha, they are within hospitalized, I overlooked that, sorry. Many thanks again!

**Comment by Sikerdebaard** [comment]
Yeah sorry, the dataset is a bit chaotic. I just needed something quick for [covid-analytics.nl](https://covid-analytics.nl) during the first wave. At first Stichting NICE only published ICU numbers, but then they added hospitalized as well so this data was added as a folder. xD

I'd rather not touch something that works, especially since other parties like you and [CoronaWatchNL](https://github.com/J535D165/CoronaWatchNL) use this data as well so a format or structure change would be annoying to these parties.

**Comment by wbijster** [comment]
Of course, I totally understand and it is quite well structured, I should just have a better look! :)
