### ISSUE TITLE
Automatic update has not run?

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/dutchcovid19data#3]
Hi, 

It seems that the automatic update is no longer running, is that correct?

Thanks, Wouter

**Comment by Sikerdebaard** [comment]
Thanks for reporting. 

Looks like there's something wrong in the datacenter. Again. I'll look into switching datacenters because frankly, datacenters shouldn't have power issues. For now I've moved it to a temporary server and it should update once an hour again. 

Sorry for the disturbance.

**Comment by wbijster** [comment]
Wow, many thanks for your excellent service again!
