### ISSUE TITLE
hospitalized/intake-cumulative.json

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/dutchcovid19data#4]
The file hospitalized/intake-cumulative.json is missing.

Not sure, but it seems due to an issue with https://www.stichting-nice.nl/covid-19/public/zkh/intake-cumulative/ that is empty?

**Comment by Sikerdebaard** [comment]
Yup, unfortunately this is a problem at the Stichting nice part. It'll appear in the repo again once Stichting nice fixes things. The script automatically skips empty request responses.

**Comment by wbijster** [comment]
Ok, thanks, do you know if they are aware? I have sent an email just to be sure, hopefully they will fix this asap.

**Comment by Sikerdebaard** [comment]
Thanks for letting them know. I'm currently on the road without a computer nearby, haven't gotten around to notifying them yet. :)

**Comment by wbijster** [comment]
FYI NICE has made the data available again (I also noticed that today's new intake at the IC was 0 and is now 28) and the hospitalized/intake-cumulative.json is available again.

**Comment by Sikerdebaard** [comment]
Thanks Wouter!

**Comment by wbijster** [comment]
FYI confirmation that it was a temporary issue, received via email from NICE this morning: "Afgelopen vrijdag werd er onderhoud gepleegd aan onze servers, waardoor de gegevens op onze site minder regelmatig geüpdatet werden. Inmiddels is alles weer up-to-date." .
