### ISSUE TITLE
raw.githubusercontent not updated

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/dutchcovid19data#5]
The most recent date of the data in https://raw.githubusercontent.com/Sikerdebaard/dutchcovid19data/master/data/intake-count.json is  2023-02-11. But in https://github.com/Sikerdebaard/dutchcovid19data/blob/master/data/intake-count.json it is 2023-02-12 (like with NICE). Can you fix the raw content please? I really appreciate that your data collection is still running! Thanks & kind regards, Wouter van Bijsterveld.

**Comment by Sikerdebaard** [comment]
This sounds like a caching issue. Have you tried adding a cachebuster variable to the requests? E.g. a unix timestamp? https://raw.githubusercontent.com/Sikerdebaard/dutchcovid19data/master/data/intake-count.json?1676229474

This prevents your browser / request library from using a cached copy.

**Comment by wbijster** [comment]
Wow, thanks, this was indeed solved after closing a notebook that still had the requests module open!
