### ISSUE TITLE
Automatic updates have stopped?

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/dutchcovid19data#6]
Hi,

It seems that the automatic update is no longer running, is that correct?

Thanks, Wouter

**Comment by Sikerdebaard** [comment]
Looks like GitHub changed its RSA/ECDSA keys. Resolving it now.

**Comment by Sikerdebaard** [comment]
Resolved, thanks for notifying. Closing.

**Comment by wbijster** [comment]
Many thanks once again!
