### ISSUE TITLE
Not all files are available

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/dutchcovid19data#7]
Some of the data files are missing, e.g died-and-survivors-cumulative.

It seems like the source data is no longer available at https://www.stichting-nice.nl/covid-19/public/zkh/died-and-survivors-cumulative/ .

Do you know if NICE stopped publishing this or changed the urls? I cannot find any news on this.

Missing are:
age-distribution-status
behandelduur-distribution
died-and-survivors-cumulative
intake-cumulative
zkh-age-distribution-status
zkh-behandelduur-distribution
zkh-intake-cumulative

**Comment by Sikerdebaard** [comment]
Hi,
The scraper has been updated. It now includes historical NICE data as well and some of the missing columns were added. Furthermore the data has been restructured in separate folders and csv exports were added. Please refer to the README.md for more information.

Unfortunately most of the missing files were removed by NICE. They are not publicly available anymore. 

Some files have columns named by index (e.g. 0, 1, 2 etc.). The names of these columns are not automatically scraped. You will have to manually infer these from the vue.js definitions in the javascript. E.g. [here](https://www.stichting-nice.nl/js/covid-19.js), [here](https://www.stichting-nice.nl/js/covid-19-zkh.js), [here](https://www.stichting-nice.nl/js/covid-19-history.js) and [here](https://www.stichting-nice.nl/js/covid-19-zkh-history.js).

Let me know if you run into issues!

**Comment by wbijster** [comment]
Many many thanks for your excellent work! I was able to load all data properly, including the historical data.
